CREATE TABLE SUBSCRIPTIONS (
    SUBJECT_ID INTEGER NOT NULL,
    CONTACT_ID INTEGER NOT NULL,
    ACCEPT SMALLINT,
    TOKEN VARCHAR(32)
);

CREATE TABLE SUBJECTS (
    SUBJECT_ID INTEGER NOT NULL,
    SUBJECT_NAME VARCHAR(80) NOT NULL
);

CREATE TABLE CONTACTS (
    CONTACT_ID INTEGER NOT NULL,
    CONTACT_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE CORR (
    CORR_ID INTEGER NOT NULL,
    CORR_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE MYPICTURES (
    NAME VARCHAR(40),
    PICTURE BLOB SUB_TYPE 0,
    CATEGORY VARCHAR(30)
);
CREATE UNIQUE INDEX RDB$3 ON MYPICTURES (CATEGORY, NAME);